backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\LoginForm;
use yii\web\UploadedFile;

/**
* Site controller
*/
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error','forgotpassword'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'changepassword', 'profile', 'edit-profile'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                   
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
   

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $login = new \app\models\LoginDetails();

        if ($model->load(Yii::$app->request->post()) ) {
            $log = \app\models\User::find()->where(['username' => $_POST['LoginForm']['username'], 'status' => 1, 'user_type'=>1])->one();
           // print_r($_POST['LoginForm']['username']);die;
            if(empty($log)) {
                \Yii::$app->session->setFlash('loginError', '<i class="fa fa-warning"></i><b> Incorrect username or password. !</b>');
                return $this->render('login', ['model' => $model]);
            }
            $login->login_user_id = $log['id'];
            $login->login_status = 1;
            $login->login_at = new \yii\db\Expression('NOW()');
            $login->user_ip_address=$_SERVER['REMOTE_ADDR'];
            $login->save(false);
            if($model->login()) {
                return $this->goBack();
            }
            else
                return $this->render('login', ['model' => $model,]);
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {

        if(isset(Yii::$app->user->id))
        \app\models\LoginDetails::updateAll(['login_status' => 0, 'logout_at'=> new \yii\db\Expression('NOW()')],'login_user_id='.Yii::$app->user->id.' AND login_status = 1');
        Yii::$app->user->logout();
        return $this->redirect(['login']);

        //return $this->goHome();
    }
    public function actionPermission()
    {
          return $this->render('denied');
    }

    public function actionProfile($id)
    {
        $model = \app\models\User::findOne($id);

        return $this->render('profile',[
                    'model'=>$model
                ]);
    }

    public function actionEditProfile($id)
    {
        $model = \app\models\User::findOne($id);
        $img=$model->profile_pic;
        if ($model->load(Yii::$app->request->post()) ) {
            $model->birth_date=date_format(date_create($_POST['User']['birth_date']),'Y-m-d');

            $model->first_name=$_POST['User']['first_name'];
            $model->username=$_POST['User']['username'];
                $model->profile_pic = UploadedFile::getInstance($model, 'profile_pic');

            // if(isset($model->photo))
            // {
            //     $image=$model->photo;
            //     $uploaddir="profile";
            //     $data = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $image));
            //     $filename=$model->id.".jpg";
            //     $image_name=time().$filename;
            //     $newname=$uploaddir."/".$image_name; 
            //     file_put_contents($newname, $data); 
            //     $filepath=Yii::$app->params['server'].''.$newname;
            //     $model->photo="";
            //     $model->profile_pic = $filepath; 
            //     //print_r($model->profile_pic);die;
            // }

             if($model->profile_pic=='')
            {
                $model->profile_pic=$img;
            }
            if ($model->profile_pic!=$img)
             { 

                 $model->profile_pic->saveAs('images/' . $model->profile_pic->baseName . '.' . $model->profile_pic->extension, false);
                 $model->profile_pic='images/'.$model->profile_pic;
                

            }
               //print_r($model->profile_pic);die;

            //print_r($_POST);die;
            if($model->save())
            {
                Yii::$app->session->setFlash('success', "Profile updated successfully."); 
                return $this->redirect(['profile', 'id'=>$id]);
            }
        }
        return $this->render('edit_profile',[
                    'model'=>$model
                ]);
    }


    public function actionChangepassword($id)
    {
        $model = \backend\models\Users::findOne($id);

        if ($model->load(Yii::$app->request->post()) )
        {
            //print_r($_POST);die;
             $oldpass=$_POST['Users']['oldpass'];
            $new_password=$_POST['Users']['newpass'];
             $password=$_POST['Users']['repeatnewpass'];

             if(sha1($oldpass)!==$model->password)
             {
              Yii::$app->session->setFlash('warning', "Old password does not match"); 
               return $this->redirect(['changepassword','id'=>$id]);
             }
          
          if($new_password!==$password)
          {
            Yii::$app->session->setFlash('warning', "New password and Confirm password must be same"); 
            return $this->redirect(['changepassword','id'=>$id]);
          }else{

            $model->password=sha1($password);

            if($model->save())
            {
                Yii::$app->session->setFlash('success', "Password change successfully."); 
                return $this->redirect(['changepassword','id'=>$id]);

            }
          }
        }

        return $this->render('changepassword',[
                    'model'=>$model
                ]);
    }

   
}

backend/views/site/changepassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Change Password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-primary">
    <div class="box-body"> 
<div class="site-changepassword">   
    <p>Please fill out the following fields to change password :</p>
   
    <?php $form = ActiveForm::begin([
        'id'=>'changepassword-form',
        'options'=>['class'=>'form-horizontal'],
        'fieldConfig'=>[
            'template'=>"{label}\n<div class=\"col-lg-3\">
                        {input}</div>\n<div class=\"col-lg-5\">
                        {error}</div>",
            'labelOptions'=>['class'=>'col-lg-2 control-label'],
        ],
    ]); ?>
        <?= $form->field($model,'oldpass',['inputOptions'=>[
            'placeholder'=>'Old Password'
        ]])->passwordInput() ?>
       
        <?= $form->field($model,'newpass',['inputOptions'=>[
            'placeholder'=>'New Password'
        ]])->passwordInput() ?>
       
        <?= $form->field($model,'repeatnewpass',['inputOptions'=>[
            'placeholder'=>'Repeat New Password'
        ]])->passwordInput() ?>
       
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-11">
                <?= Html::submitButton('Change password',[
                    'class'=>'btn btn-primary'
                ]) ?>
            </div>
        </div>
    <?php ActiveForm::end(); ?>
</div>
</div>
</div>

backend/views/site/denied.php
<?php 
	$this->title = 'Access Denied';

?>
<div class="site-error">

    <div class="alert alert-danger">
        <span class="fa fa-warning"></span> Access is denied!
    </div>

    <p>
        You don't have permission to access this module.
    </p>
    <p>
        Please refer to your system administrator. Thank you.
    </p>

</div>

backend/views/site/edit_profile.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\db\Query;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use kartik\date\DatePicker;

$User=\app\models\User::find()->where(['id' =>  Yii::$app->user->id])->one();
$authorname=$User->first_name." ".$User->last_name;
$model->created_at = date('Y-m-d H:i:s');
/* @var $this yii\web\View *//* @var $model backend\models\About */
/* @var $form yii\widgets\ActiveForm */
?>
<script src="<?php echo Yii::$app->params['image']?>js/ckeditor/ckeditor.js"></script>

<div class="about-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <div class="box box-primary">
      <div class="box-header with-border">
        <div class="col-md-8">
            <h3 class="box-title"> <i class="fa fa-pencil"></i> Add Details</h3>
        </div>
        <div class="col-md-4">
            <div class="pull-right">
                <?= Html::submitButton('Save', ['id'=>'submit_upper','class' => 'btn btn-success']) ?>
                <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
            </div>
        </div>
      </div>
      <div class="box-body">
        <div class="row">
            <div class="col-md-7">
                <div class="form-group">
                    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true, 'class'=>'form-control']) ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'username')->textInput(['maxlength' => true, 'class'=>'form-control', 'readonly'=>true]) ?>
                </div>
                <div class="form-group">
                  <?php $value="";
                      if(!$model->isNewRecord)
                      {
                        $value=($model->birth_date!="0000-00-00" && $model->birth_date!=null) ? date('d-m-Y', strtotime($model->birth_date)): "";
                      }      
                        echo $form->field($model, 'birth_date')->widget(DatePicker::classname(), [
                              'name' => 'birth_date', 
                              'options' => [//'placeholder' => 'Select issue date ...'
                              'value'=>$value,
                                      ],
                              'pluginOptions' => [
                                  'format' => 'dd-mm-yyyy',
                                  'todayHighlight' => true
                              ]
                          ]);
                    ?>
                </div>
                <div class="form-group">
                    <details class="claro-details" open="">    <summary role="button" aria-expanded="true" aria-pressed="true" class="claro-details__summary js-form-required form-required">Image<span class="required-mark"></span></summary><div class="claro-details__wrapper details-wrapper">
                          <div class="js-form-item form-item js-form-type-managed-file form-type--managed-file js-form-item-field-image-0 form-item--field-image-0">
                          <label for="edit-field-image-0-upload" id="edit-field-image-0--label" class="form-item__label js-form-required form-required">Add a new file</label>
                            <div class="image-widget js-form-managed-file form-managed-file form-managed-file--image is-single has-upload no-value no-meta">
                                <div class="form-managed-file__main">
                                    <?php echo $form->field($model, 'profile_pic')->fileInput(['class'=>'form-element'])->label(false) ?>

                                   
                                </div>
                            </div>
                            <div id="edit-field-image-0--description" class="form-item__description">
                            One file only.<br>2 MB limit.<br>Allowed types: png gif jpg jpeg.<br>Image Size: 195x250
                        </div>
                      </div>
                      </div>
                    </details>
                </div>
                
                
            </div>
            <div class="col-md-5">
                <div class="entity-meta accordion js-form-wrapper form-wrapper" id="edit-advanced">
                  <div class="entity-meta__header accordion__item js-form-wrapper form-wrapper" id="edit-meta">
                      
                      <div class="entity-meta__last-saved js-form-item form-item js-form-type-item form-type--item js-form-item-meta-changed form-item--meta-changed" id="edit-meta-changed">
                         <label for="edit-meta-changed" class="form-item__label">Last saved</label>
                         Not saved yet
                      </div>
                      <div class="entity-meta__author js-form-item form-item js-form-type-item form-type--item js-form-item-meta-author form-item--meta-author" id="edit-meta-author">
                        <label for="edit-meta-author" class="form-item__label">Author</label>
                         <?= $authorname;?>
                      </div>
                      <div class="entity-meta__author js-form-item form-item js-form-type-item form-type--item js-form-item-meta-author form-item--meta-author" id="edit-meta-author">
                        <label for="edit-meta-author" class="form-item__label">Creation Date</label>
                        <?= $form->field($model, 'created_at')->hiddenInput(['value' => $model->created_at])->label(false); ?>

                         <?= date_format(date_create($model->created_at),'d-m-Y H:i:s');?>
                      </div>
                  </div>
                
                </div>
            </div>
        </div>
       </div>
       <!-- /.box-body -->
        <div class="box-footer">
          <?= Html::submitButton('Save', ['id'=>'submit_lower','class' => 'btn btn-success']) ?>
          <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
        </div>

    </div>
    <?php ActiveForm::end(); ?>

</div>
<div id="uploadimageModal" class="modal" role="dialog">
    <div class="modal-dialog" style="min-width:630px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Upload & Crop Image</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8 text-center">
                        <div id="image_demo" style=" margin-top:30px"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4" style="padding-top:30px;">
                       
                          <button class="btn btn-success crop_image">Crop & Upload Image</button>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript">

$(document).ready(function(){

    $image_crop = $('#image_demo').croppie({
    enableExif: true,
    viewport: {
      width:220,
      height:220,
      type:'square' //circle
    },
    boundary:{
      width:200,
      height:200
    }
  });
  $('#user-profile_pic').on('change', function(){
    var reader = new FileReader();
    reader.onload = function (event) {
      $image_crop.croppie('bind', {
        url: event.target.result
      }).then(function(){
        console.log('jQuery bind complete');
      });
    }
    reader.readAsDataURL(this.files[0]);
    $('#uploadimageModal').modal('show');
  });



  $('.crop_image').click(function(event){
    $image_crop.croppie('result', {
      type: 'canvas',
      size: 'viewport'
    }).then(function(response){
        $('#uploadimageModal').modal('hide');
        $("#preview_profile_photo").attr("src",response);
        $("#user-photo").val(response);
     
    })
  });

});  
$("#submit_lower").mousedown(function(){
  for (var i in CKEDITOR.instances){
    CKEDITOR.instances[i].updateElement();
  }
});
$("#submit_upper").mousedown(function(){
  for (var i in CKEDITOR.instances){
    CKEDITOR.instances[i].updateElement();
  }
});

</script>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/forgotpassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Forgot Password';

?>

<div class="login-box">
    <div class="login-logo">
        <a href="#"><img src="<?= Yii::$app->params['logo']?>" /></a>
    </div>
    <!-- /.login-logo -->
    <div id="om-lightbox-case-study-optin-bar" class="boston-clearfix boston-optin-bar om-clearfix"><span class="boston-bar boston-yellow-bar om-bar om-red-bar"></span><span class="boston-bar boston-black-bar om-bar om-blue-bar"></span><span class="boston-bar boston-yellow-bar om-bar om-red-bar"></span><span class="boston-bar boston-black-bar om-bar om-blue-bar"></span></div>
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form->field($model,'username',['inputOptions'=>[
            'placeholder'=>'Username'
        ]])->textInput() ?>
       
        <?= $form->field($model,'newpass',['inputOptions'=>[
            'placeholder'=>'New Password'
        ]])->passwordInput() ?>
       
        <?= $form->field($model,'repeatnewpass',['inputOptions'=>[
            'placeholder'=>'Repeat New Password'
        ]])->passwordInput() ?>

        <div class="row">
           
            <div class="col-xs-12">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
                <?= Html::a(
                                    'Back to login',
                                    ['site/login'],
                                    ['class' => 'btn btn-primary btn-block btn-flat']
                                ) ?>
            </div>
            <!-- /.col -->
        </div>

        <?php ActiveForm::end(); ?>
         
    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->
<style type="text/css">
    .login-page, .register-page {
    height: auto;
    background: #d2d6de;
    display: block;
    position: fixed;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
    background: url(<?= Yii::$app->params['image']?>images/bg.png) transparent;
    background-size: auto 100%;
    z-index: -1;
}
.btn-primary {
    background-color: #e7a54f!important;
    border-color: #e7a54f!important;
}
.btn-primary:hover {
    background-color: #fff!important;
    border-color: #e7a54f!important;
    color: #e7a54f;
}
.boston-optin-bar {
    margin-bottom: 20px;
}
.boston-yellow-bar {
    background-color: #e7a54f;
}
.boston-bar {
    float: left;
    width: 25%;
    height: 11px;
    display: block;
}
.boston-black-bar {
    background-color: #191919;
}
</style>

backend/views/site/index.php
<?php
use backend\models\Vehicles;
use backend\models\Company;
use backend\models\Transporter;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
$this->title = 'Dashboard';

?>

<!-- <div class="site-index">
    
    <div class="body-content">
    
      <div class="card">
        <div class="card-body"> -->
           <!--  <div class="card-title d-flex justify-content-between align-items-center">
                
                <div class="slick-single-arrows">
                    <a class="btn btn-outline-info  btn-sm">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a class="btn btn-outline-info btn-sm">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>
            </div>
            <div class="row slick-single-item"> 
            	<div class="col-md-2 grid-margin stretch-card">
		          <a href="#">
		            <div class="card border-0 border-radius-2 bg-success">
		              <div class="card-body">
		                <div class="d-flex flex-md-column flex-xl-row flex-wrap  align-items-center justify-content-between">
		                  <div class="icon-rounded-inverse-success icon-rounded-lg icon">
		                    <img src="<?= Yii::$app->params['image'];?>images/icons/celebrity-yellow.svg" />
		                  </div>
		                  <div class="text-white m-auto">
		                    <div class="d-flex flex-md-column flex-xl-row flex-wrap align-items-baseline align-items-md-center align-items-xl-baseline">
		                      <h3 class="mb-0 mb-md-1 mb-lg-0 mr-1">Article</h3>
		                    </div>
		                  </div>
		                </div>
		              </div>
		            </div>
		          </a>
		        </div>
                <div class="col-md-2 grid-margin stretch-card">
		          <a href="#">
		            <div class="card border-0 border-radius-2 bg-success">
		              <div class="card-body">
		                <div class="d-flex flex-md-column flex-xl-row flex-wrap  align-items-center justify-content-between">
		                  <div class="icon-rounded-inverse-success icon-rounded-lg icon">
		                    <img src="<?= Yii::$app->params['image'];?>images/icons/celebrity-yellow.svg" />
		                  </div>
		                  <div class="text-white m-auto">
		                    <div class="d-flex flex-md-column flex-xl-row flex-wrap align-items-baseline align-items-md-center align-items-xl-baseline">
		                      <h3 class="mb-0 mb-md-1 mb-lg-0 mr-1">FAQ's</h3>
		                    </div>
		                  </div>
		                </div>
		              </div>
		            </div>
		          </a>
		        </div>
		        <div class="col-md-2 grid-margin stretch-card">
		          <a href="#">
		            <div class="card border-0 border-radius-2 bg-success">
		              <div class="card-body">
		                <div class="d-flex flex-md-column flex-xl-row flex-wrap  align-items-center justify-content-between">
		                  <div class="icon-rounded-inverse-success icon-rounded-lg icon">
		                    <img src="<?= Yii::$app->params['image'];?>images/icons/celebrity-yellow.svg" />
		                  </div>
		                  <div class="text-white m-auto">
		                    <div class="d-flex flex-md-column flex-xl-row flex-wrap align-items-baseline align-items-md-center align-items-xl-baseline">
		                      <h3 class="mb-0 mb-md-1 mb-lg-0 mr-1">Birthday Stars</h3>
		                    </div>
		                  </div>
		                </div>
		              </div>
		            </div>
		          </a>
		        </div>
              	<div class="col-md-2 grid-margin stretch-card">
		          <a href="#">
		            <div class="card border-0 border-radius-2 bg-success">
		              <div class="card-body">
		                <div class="d-flex flex-md-column flex-xl-row flex-wrap  align-items-center justify-content-between">
		                  <div class="icon-rounded-inverse-success icon-rounded-lg icon">
		                    <img src="<?= Yii::$app->params['image'];?>images/icons/celebrity-yellow.svg" />
		                  </div>
		                  <div class="text-white m-auto">
		                    <div class="d-flex flex-md-column flex-xl-row flex-wrap align-items-baseline align-items-md-center align-items-xl-baseline">
		                      <h3 class="mb-0 mb-md-1 mb-lg-0 mr-1">Celebrity Profile</h3>
		                    </div>
		                  </div>
		                </div>
		              </div>
		            </div>
		          </a>
		        </div>
              	
              	
            </div> -->
           <!--  <div class="row">
                <div class="col-lg-3 col-xs-6"> -->
                  <!-- small box -->
                  <!-- <div class="small-box bg-yellow">
                    <div class="inner">
                      <h3>Daily</h3>

                      <p>Excel Upload</p>
                    </div>
                    <div class="icon">
                      <i class="fa fa-file-excel-o"></i>
                    </div>
                    <a href="<?= \yii\helpers\Url::to(['daily-upload/create'])?>" class="small-box-footer">
                      Click Here <i class="fa fa-arrow-circle-right"></i>
                    </a>
                  </div>
                </div> -->
               <!--  <div class="col-lg-3 col-xs-6">
                  small box
                  <div class="small-box bg-yellow">
                    <div class="inner">
                      <h3>Weekly</h3>

                      <p>Excel Upload</p>
                    </div>
                    <div class="icon">
                      <i class="fa fa-file-excel-o"></i>
                    </div>
                    <a href="<?= \yii\helpers\Url::to(['weekly-upload/create'])?>" class="small-box-footer">
                      Click Here <i class="fa fa-arrow-circle-right"></i>
                    </a>
                  </div>
                </div>
                <div class="col-lg-3 col-xs-6"> -->
                  <!-- small box -->
                  <!-- <div class="small-box bg-yellow">
                    <div class="inner">
                      <h3>Monthly</h3>

                      <p>Excel Upload</p>
                    </div>
                    <div class="icon">
                      <i class="fa fa-file-excel-o"></i>
                    </div>
                    <a href="<?= \yii\helpers\Url::to(['monthly-upload/create'])?>" class="small-box-footer">
                      Click Here <i class="fa fa-arrow-circle-right"></i>
                    </a>
                  </div>
                </div> -->
                <!-- <div class="col-lg-3 col-xs-6">
                  small box
                  <div class="small-box bg-yellow">
                    <div class="inner">
                      <h3>Yearly</h3>

                      <p>Excel Upload</p>
                    </div>
                    <div class="icon">
                      <i class="fa fa-file-excel-o"></i>
                    </div>
                    <a href="<?= \yii\helpers\Url::to(['yearly-upload/create'])?>" class="small-box-footer">
                      Click Here <i class="fa fa-arrow-circle-right"></i>
                    </a>
                  </div>
                </div>
            </div> -->
        <!-- </div>
    </div>
  </div>
</div> -->
 
 <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js'></script>
  <script src='<?php echo Yii::$app->params['image']?>js/slick.min.js'></script>
  <script type="text/javascript">
  	
  	$(document).ready(function () { 
     if ($('.slick-single-item').length) {
        $('.slick-single-item').slick({
            autoplay: true,
            autoplaySpeed: 3000,
            infinite: true,
            slidesToShow: 4,
            slidesToScroll: 4,
            prevArrow: '.slick-single-arrows a:eq(0)',
            nextArrow: '.slick-single-arrows a:eq(1)',
            responsive: [
                {
                    breakpoint: 1300,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3,
                    }
                },
                {
                    breakpoint: 992,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3,
                    }
                },
                {
                    breakpoint: 768,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2
                    }
                },
                {
                    breakpoint: 540,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1
                    }
                }
            ]
        });
    }
  });
  </script>
  <style type="text/css">
      .bg-yellow{
        background: #E79E44;
      }
  </style>

backend/views/site/profile.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Profile';
$this->params['breadcrumbs'][] = $this->title;
// $starsign=\backend\models\Starsign::find()->where(['status'=>1])->all();

?>
<div class="row gutters-sm">
  <div class="col-md-4 mb-3">
    <div class="card">
      <div class="card-body">
        <div class="d-flex flex-column align-items-center text-center">
          <?php if($model->profile_pic=="" && $model->profile_pic==null) {
            echo '<img src="'.Yii::$app->params['server'].'images/user.jpg" alt="Admin" class="rounded-circle" width="150">';
            }
            else
              {
                echo '<img src="'.Yii::$app->params['server'].$model->profile_pic.'" alt="Admin" class="rounded-circle" width="150">';
              }?>
          <div class="mt-3">
            <h4><?= $model->first_name?></h4>
            <p class="text-secondary mb-1">Administrator</p><br />
             <a class="btn btn-primary" href="<?= \yii\helpers\Url::to(['site/edit-profile','id'=>Yii::$app->user->identity->id])?>"><i class="fa fa-pencil"></i> Edit Profile</a>
          </div>
        </div>
      </div>
    </div>
    
  </div>
 
</div>
       

<style type="text/css">
  .nav{display:block;}

</style>