backend/models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\helpers\Security;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property int $id
 * @property string $username
 * @property string $password
 * @property int $status
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    /**
     * {@inheritdoc}
     */
    public $photo;
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'password'], 'required'],
            [['status'], 'integer'],
            [['username', 'password'], 'string', 'max' => 100],
            [['photo'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'password' => 'Password',
            'status' => 'Status',
        ];
    }

    /**
     * {@inheritdoc}
     * @return UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserQuery(get_called_class());
    }


    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
/* modified */
    public static function findIdentityByAccessToken($token, $type = null)
    {
          return static::findOne(['access_token' => $token]);
    }
 
/* removed
    public static function findIdentityByAccessToken($token)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
*/
    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

   
    /**
     * Finds user by password reset token
     *
     * @param  string      $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        $expire = \Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return trim($this->password) === sha1($password);

        //return $this->password === sha1($password);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Security::generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Security::generateRandomKey();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Security::generateRandomKey() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function getName()
    {
        return Yii::$app->user->identity->first_name;
    }
}

backend/models/Users.php
<?php

namespace backend\models;

use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\db\Query;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property int $id
 * @property string $username
 * @property string $password
 * @property int $status
 */
class Users extends \yii\db\ActiveRecord 
{
    /**
     * {@inheritdoc}
     */
    public $oldpass;
    public $newpass;
    public $repeatnewpass;
    public $fullname;
    public $first_name;
    const SCENARIO_REPORT = 'report';
    const SCENARIO_CREATE = 'create';
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
           [['first_name','email', 'password', ], 'required',  'on' => self::SCENARIO_CREATE],
            [['starsign','birth_date'], 'safe'],
            [['email'], 'unique', 'on' => self::SCENARIO_CREATE],
           // [['email'], 'unique', 'targetAttribute' => 'status'],


            [['email_id'], 'UniqueRules', 'on' => 'resetpassword'],
            [['oldpass', 'newpass', 'repeatnewpass'], 'required', 'on' => 'resetpassword'],
           // ['repeatnewpass','compare','compareAttribute'=>'newpass'],
            [['status'], 'integer'],
            [['username', 'password'], 'string', 'max' => 100],
            ['email', 'email'],
            [['first_name','last_name','user_id','email_id', 'password', 'created_at', 'fullname'],'safe'], 
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'password' => 'Password',
            'status' => 'Status',
            'oldpass'=>'Old Password',
            'newpass'=>'New Password',
            'repeatnewpass'=>'Confirm Password',
            'user_id' => 'User',
            'email_id' => 'Email/Username',
            'star_sign' => 'Star Sign',
            'birth_date' => 'Birth Date',
            'first_name' => 'Name'
        ];
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }
    public static function getUsers()
    {
        return parent::findAll(['status' =>1]);
   }
    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Security::generateRandomKey();
    }

  
    public function getName()
    {
        return Yii::$app->user->identity->name;
    }

    public function UniqueRules()
    {
        if(!empty($this->email)){
            $unique=User::find()->where(['email'=>$this->email])->count();

            if($unique>0)
            {
                $this->addError('email','Email already exists');
            }
            
        }
    }

    public function UniqueUsernameRules()
    {
        
            $query=new Query;
            $query->from('user')
                    ->where(['email' => $this->email, 'status'=>1]);
            $command = $query->createCommand();
            $User = $command->queryOne(); 
            
            if($User!="" && $this->id!=$User['id'])
            {
                $this->addError('email','Email must be unique');
            }
    }

    
    public function getCompany()
    {
        return $this->hasOne(Company::className(), ['id' => 'company_id']);
    }
}

backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Users;
use app\models\User;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\data\ActiveDataProvider;

use backend\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use fedemotta\datatables\DataTables;

/**
 * UsersController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $status="";
       
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$status);
        $model=new Users();
        $model->scenario = Users::SCENARIO_REPORT;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model
        ]);
        
    }

    public function actionAdd()
    {
        $model = new Users();
        $model->scenario = Users::SCENARIO_CREATE;
        if ($model->load(Yii::$app->request->post())) {
            $model->created_at=date('Y-m-d H:i:s');
          $model->username=$_POST['Users']['email'];
          $model->birth_date=date_format(date_create($_POST['Users']['birth_date']),'Y-m-d');
          $model->password=sha1($model->password);
          if($model->save())
          {
                Yii::$app->session->setFlash('success', "User created successfully"); 
                return $this->redirect(['index']);
          }
        }

        return $this->render('create', [
          'model' => $model,
        ]);
        
    }
    public function actionAddSubscription()
    {
        $model = new \backend\models\Cart();
        $model->scenario = \backend\models\Cart::SCENARIO_CREATE;
        if ($model->load(Yii::$app->request->post())) {
           $status="";
           $model->status='Confirmed';
           $model->start_date=date_format(date_create($_POST['Cart']['start_date']),'Y-m-d');
           $model->end_date=date_format(date_create($_POST['Cart']['end_date']),'Y-m-d');
           if($model->save())
           {
            if($_POST['Cart']['status']=='Confirm')
                $status='succeeded';

                $user=Users::findOne($model->user_id);
                $name=$user->first_name;
                $email=$user->email;
                $subscription=\backend\models\Subscription::findOne($model->item_id);
                $amount=$subscription->amount;
                $payment = new \backend\models\TblPayment();
                $payment->email=$email;
                $payment->user_id=$model->user_id;
                $payment->currency_code='gbp';
                $payment->payment_status=$status;
                $payment->amount=$amount;
                $payment->create_at=date('Y-m-d H:i:s');
                $payment->txn_id='0';
                $payment->payment_response='-';
                if($payment->save())
                {
                    //print_r($payment->errors);die;
                    $orders = new \backend\models\Orders();
                    $orders->scenario = \backend\models\Orders::SCENARIO_CREATE;
                   
                    $orders->user_id=$model->user_id;

                    $orders->payment_id=$payment->id;

                    $orders->cart_id=$model->id;
                   
                    $orders->name=$name;
                    
                    $orders->email=$email;

                    $orders->payment_status=$status;

                    $orders->created_date=date('Y-m-d H:i:s');
                    $orders->amount=$amount;
                    if($orders->save())
                    {
                        Yii::$app->session->setFlash('success', "Subscription added for '".$name."' successfully"); 
                        return $this->redirect(['subscription']);

                    }
                    else
                    {
                       // print_r($orders->errors);die;
                    }

                }
                else
                {
                 // print_r($payment->errors);die;
                }
                
           }
           else
           {
            //print_r($model->errors);die;
           }
        }
       
        return $this->render('create_subscription', [
          'model' => $model,
        ]);
        
    }
    public function actionSubscription()
    {
       // $searchModel = new \backend\models\CartSearch();
        $query = \backend\models\Cart::find()
                     ->select('cart.id as id, ML.id as orderid, cart.item_id, cart.user_id, cart.session_id, cart.created_at, cart.start_date, cart.end_date, cart.ip_address, cart.starsign, cart.status, cart.is_chart')
                     ->join('LEFT JOIN', 'orders AS ML', 'ML.cart_id = cart.id')
                     ->where('cart.is_chart = :is_chart', [':is_chart' => 0])
                     ->andWhere('cart.status = :status', [':status' => 'Confirmed'])
                    ->andWhere('ML.payment_status = :payment_status', [':payment_status' => 'succeeded']);
                   // ->asArray()->all();
      //  $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
      $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        return $this->render('subscription', [
           // 'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionGetenddate()
    {
        $date=$_REQUEST['date'];
      $duration=$_REQUEST['duration'];
        $fulldate = strtotime($date);
        $new_date = strtotime('+ '.$duration.' month', $fulldate);
        $end_date= date('d-m-Y', $new_date);
        return $end_date;


    }

    public function actionUpdateSubscription($id)
    {
        $model = \backend\models\Cart::findOne($id);

        //print_r($model);
        $model->scenario = \backend\models\Cart::SCENARIO_CREATE;
        if ($model->load(Yii::$app->request->post())) {
           $status="";
           $model->status='Confirmed';
           $model->start_date=date_format(date_create($_POST['Cart']['start_date']),'Y-m-d');
           $model->end_date=date_format(date_create($_POST['Cart']['end_date']),'Y-m-d');
           if($model->save())
           {
           
                $user=Users::findOne($model->user_id);
                $name=$user->first_name;
                Yii::$app->session->setFlash('success', "Subscription of ".$name." updated successfully"); 
                return $this->redirect(['subscription']);    
           }
        }
       
        return $this->render('update_subscription', [
          'model' => $model,
        ]);
        
    }
    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
   

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

   
    public function actionChangestatus($id,$flag)
    {
        $success=Yii::$app->db->createCommand()
                    ->update('user', [
                    'status'=>$flag
                    ],'id = '. $id)->execute();
 
        return $this->redirect(['index']);

    }
    public function actionUnblock($id,$flag)
    {
        $success=Yii::$app->db->createCommand()
                    ->update('user', [
                    'status'=>1
                    ],'id = '. $id)->execute();
        return $this->redirect(['index']);

    }

    public function actionGetcompanywiselisting( $status)
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $status);
        $data="";
        echo  DataTables::widget([
                  'dataProvider' => $dataProvider,
                  'id'=>'result',
                  'clientOptions' => [
                      'lengthMenu' => [200],
                      'responsive' => true, 
                      'dom' => 'BfTrtip',
                      'buttons' => [
                        'csv','excel', 'pdf', 'print'
                        ]
                    ],
                  'columns' => [

backend/views/users/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User 
<h1><?= Html::encode($this->title) ?></h1>*/

$this->title = 'Add User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li class="active"><a href="<?= \yii\helpers\Url::to(['users/index']); ?>">User</a></li>
              <li><a href="<?php echo \yii\helpers\Url::to(['users/subscription']); ?>" >Add Subscription</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="tab_1">
                  <div class="row setup-content" id="step-1">
                    <div class="col-xs-12">
                        <div class="col-md-12">
                          <?= $this->render('_form', [
						        'model' => $model,
						        //'user_type'=>$user_type
						    ]) ?>
                        </div>
                    </div>
                  </div>
                  
              </div>
              <!-- /.tab-pane -->
             
              
              <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
        </div>

    

</div>

backend/views/users/create_subscription.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User 
<h1><?= Html::encode($this->title) ?></h1>*/

$this->title = 'Add Subscription';
$this->params['breadcrumbs'][] = ['label' => 'Subscription', 'url' => ['subscription']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li><a href="<?= \yii\helpers\Url::to(['users/index']); ?>">User</a></li>
              <li  class="active"><a href="<?php echo \yii\helpers\Url::to(['users/subscription']); ?>" >Add Subscription</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="tab_1">
                  <div class="row setup-content" id="step-1">
                    <div class="col-xs-12">
                        <div class="col-md-12">
                          <?= $this->render('_form_subscription', [
          						        'model' => $model,
          						        //'user_type'=>$user_type
          						    ]) ?>
                        </div>
                    </div>
                  </div>
                  
              </div>
              <!-- /.tab-pane -->
             
              
              <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
        </div>

    

</div>

backend/views/users/subscription.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use backend\models\Users;
use backend\models\Cart;
use fedemotta\datatables\DataTables;
/* @var $this yii\web\View */
/* @var $model app\models\User 
<h1><?= Html::encode($this->title) ?></h1>*/

$this->title = 'Add Subscription';
$this->params['breadcrumbs'][] = ['label' => 'Subscription', 'url' => ['subscription']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li><a href="<?= \yii\helpers\Url::to(['users/add']); ?>">User</a></li>
              <li  class="active"><a href="<?php echo \yii\helpers\Url::to(['users/subscription']); ?>" >Add Subscription</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="tab_1">
                  <div class="row setup-content" id="step-1">
                    <div class="col-xs-12">
                        <div class="col-md-12">
                            <div class="Orders-index">
                               <div class="box box-primary" style="border:0">
                                  <div class="box-header with-border">
                                    <div class="col-md-6">
                                        <h3 class="box-title"> <i class="fa fa-list"></i> Subscription</h3>
                                    </div>
                                    <div class="col-md-6">
                                      <div class="pull-right">
                                        <?= Html::a('<i class="fa fa-plus"></i>', ['add-subscription'], ['class' => 'btn btn-success', 'data-toggle'=>"tooltip", 'data-original-title'=>"Add New"]) ?>
                                       
                                      </div>
                                    </div>
                                  </div>
                                   <div class="box-body">
                                    <?php //print_r($dataProvider);die;?>
                                      <?= DataTables::widget([
                                              'dataProvider' => $dataProvider,
                                              'clientOptions' => [
                                              'lengthMenu' => [200],
                                              'responsive' => true, 
                                              'dom' => 'BfTrtip',
                                              'buttons' => [
                                                'csv','excel', 'pdf', 'print'
                                              ]
                                             ],
                                              'columns' => [
                                                 // ['class' => 'yii\grid\SerialColumn'],
                                                'orderid',
                                                 [
                                                   'attribute' => 'id',
                                                   'format' => 'raw',
                                                    'value'=>function($model) {
                                                      return Html::a($model->id,['/users/update-subscription', 'id' => $model->id]);
                                                    },
                                                  ], 
                                                  [
                                                    'label'=>'Type',
                                                    'attribute'=>'id',
                                                    'format' => 'raw',
                                                    'value' => function ($data) {
                                                            return getItemType($data['item_id'],1);
                                                     },
                                                  ],
                                                         'starsign',
                                                         [
                                                            'label'=>'Subscription start date',
                                                            'attribute'=>'start_date',
                                                            'format' => 'raw',
                                                            'value' => function ($data) {
                                                                return date_format(date_create($data->start_date),'d-m-Y');
                                                             },
                                                          ], 
                                                          [
                                                            'label'=>'Subscription end date',
                                                            'attribute'=>'end_date',
                                                            'format' => 'raw',
                                                            'value' => function ($data) {
                                                                return date_format(date_create($data->end_date),'d-m-Y');
                                                             },
                                                          ], 
                                                         [
                                                            'label'=>'Email',
                                                            'attribute'=>'user_id',
                                                            'format' => 'raw',
                                                            'value' => function ($data) {
                                                                    return getUsername($data['user_id'], 1);
                                                             },
                                                          ],                      
                                                          [
                                                            'label'=>'Name',
                                                            'attribute'=>'user_id',
                                                            'format' => 'raw',
                                                            'value' => function ($data) {
                                                                    return getUsername($data['user_id'],2);
                                                             },
                                                          ],
                                                        
                                                          [
                                                              'label'=>'Amount',
                                                              'attribute'=>'id',
                                                              'format' => 'raw',
                                                              'value' => function ($data) {
                                                                      return getItemType($data['item_id'],2);
                                                               },
                                                          ],
                                                          //'payment_status',
                                                            
                                                          [
                                                              'attribute'=>'created_at',
                                                               'value' => function ($model) {
                                                                 return date_format(date_create($model->created_at),'d-m-Y'); 
                                                                },
                                                                'headerOptions' => ['style' => 'width:10%'],
                                                          ]
                                                          
                                                          
                                                      ],
                                                  ]);?>

                                    <?php 

                                    function getItemType($cart_id, $flag)
                                    {        
                                      $title="";$amount=0;   
                                        $Cart = \backend\models\Cart::find()->where(['id'=>$cart_id])->one();
                                        if($Cart->is_chart==0)
                                        {
                                             $data = \backend\models\Subscription::find()->where(['id'=>$Cart->item_id])->one();
                                             $title=$data->name;
                                             $amount=$data->amount;
                                        }
                                        else
                                        {
                                            $data = \backend\models\Charts::find()->where(['id'=>$model->item_id])->one();
                                            $title=$data->title;
                                            $amount=$data->price;
                                        }
                                        if($flag==1)
                                          return $title;
                                        else
                                          return "£" .$amount;
                                    } 
                                    function getAmount($payment_id)
                                    {
                                         $TblPayment = \backend\models\TblPayment::find()->where(['id'=>$payment_id])->one();
                                                return $TblPayment->amount." ".$TblPayment->currency_code;
                                    }
                                    function getUsername($user_id, $flag)
                                    {
                                      $Users = \backend\models\Users::find()->where(['id'=>$user_id])->one();
                                      if($flag==1)
                                        return $Users->email;
                                      else
                                        return $Users->first_name;
                                    }
                                    ?>
                                  </div> 
                            </div>
                            </div>
                        </div>
                    </div>
                  </div>
                  
              </div>
              <!-- /.tab-pane -->
             
          </div>
            <!-- /.tab-content -->
        </div>

    

</div>

backend/views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Update User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->first_name." ".$model->last_name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">
<?php 
     echo $this->render('_form_update', [
                'model' => $model,]);
?>

</div>